### ISSUE TITLE
Add a .gitignore file

### ISSUE THREAD

**Issue by rgupta-okta** [shawneetap/SoundCloud#6]
include node_modules and sass cache files

**Comment by shawneetap** [comment]
Alright I got it. Did you receive a message? Sorry, Im still a little confused about GitHubs workflow. fixes #6

**Comment by rgupta-okta** [comment]
So in git there's a commit, In the Commit you can say something like fixes #6, so that when you submit a Pull Request, which you can mention me in the description to notify me to look at the changes and maybe comment on them before you merge your pull request, and merge it to master, this issue will close. So two things.
1. Add fixes issue number in your commit messages
2. Mention me or something on a PR if you want me to look at it before merging it to master, so that we can fix it before it goes in.

Look up git-flow for more understanding.

**Comment by shawneetap** [comment]
Im going through some tutorials right now for github. Do you use the Github Desktop client or is it better to learn how to push github changes through the terminal?

**Comment by rgupta-okta** [comment]
terminal!

**Comment by shawneetap** [comment]
Hahaha! Right on.

**Comment by shawneetap** [comment]
Cool, alright I added watch to the Gruntfile.js and made a pull request pr/4 all using terminal. I think I still a little confused about the workflow i.e. I dont think I was supposed to merge the pr/4 with the master just yet, but I didnt know how else to push it to GitHub.

**Comment by shawneetap** [comment]
scratch that. I didnt merge pr/4 with the master.

**Comment by rgupta-okta** [comment]
https://guides.github.com/introduction/flow/
